### PR TITLE
add a directory

### PR DESCRIPTION
**Pull request by krish-adi**
This PR adds a directory path with a few links of llms.txt in the wild.

### CODE REVIEW

**Comment by jph00** [comment]
Maybe it would be better to link on the home page to a couple of llms.txt directories? Otherwise we'd have to maintain our own directory.

**Comment by krish-adi** [comment]
@jph00 if I understand, you'd like to have links of the directories in the homepage and not the links of the websites having the llmstxt ?

**Comment by jph00** [comment]
Yes exactly!

**Comment by krish-adi** [comment]
Yup this is ready now :)

**Comment by jph00** [comment]
Many thanks!

**Pull request merged**
